# Generated by Django 2.2.9 on 2020-01-30 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tutorial_app", "0004_auto_20200120_1113"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
