# Generated by Django 2.2.9 on 2020-02-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorial_app", "0005_idea_author"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[],),
        migrations.AddField(
            model_name="user",
            name="user_group",
            field=models.CharField(
                choices=[("owner", "owner"), ("admin", "admin"), ("staff", "staff")],
                default="staff",
                max_length=50,
            ),
        ),
    ]
