# Generated by Django 2.2.9 on 2020-02-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_app', '0006_user_user_group'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
