# Generated by Django 2.2.9 on 2020-02-26 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("multitenant_app", "0002_auto_20200224_0942"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="owner_of_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner",
                to="multitenant_app.Company",
            ),
        ),
    ]
